name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Generate Hive adapters
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/habitsxd.jks

      - name: Build APK (split per ABI)
        run: flutter build apk --release --split-per-abi
        env:
          CI: true
          KEYSTORE_PATH: habitsxd.jks
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: habitsxd-apk-release
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 7
